"use client";

import { useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { currency, formatDate } from "@/lib/utils";
import { SignaturePreview } from "./SignaturePad";
import type { ClientDocumentType } from "@/types";

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex justify-between gap-4 border-b border-slate-200 py-2 text-sm">
      <span className="text-slate-500">{label}</span>
      <span className="text-right font-medium text-slate-900">{value}</span>
    </div>
  );
}

export function DocumentView({ doc }: { doc: ClientDocumentType }) {
  const [origin, setOrigin] = useState("");
  useEffect(() => setOrigin(window.location.origin), []);

  const s: any = doc.snapshot || {};
  const verifyUrl = `${origin}/verify/${doc.referenceNumber}`;
  const isInvoice = ["invoice", "final-invoice", "milestone-invoice", "quotation"].includes(String(doc.type));
  const isContract = doc.type === "contract" || doc.type === "maintenance-agreement";
  const isHandover = doc.type === "handover-certificate";

  return (
    <div className="print-area mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-8 text-slate-900 shadow-sm">
      {doc.aiGenerated && doc.status !== "approved" && (
        <div className="mb-4 rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-center text-xs font-semibold text-amber-700">
          ⚠️ Generated by AI — Pending Developer Approval
        </div>
      )}
      {/* Header */}
      <div className="flex items-start justify-between gap-6 border-b-2 border-emerald-500 pb-5">
        <div className="flex items-center gap-4">
          {s.company?.logo ? (
            <img src={s.company.logo} alt="Logo" className="h-14 w-14 rounded-lg object-cover" />
          ) : (
            <div className="flex h-14 w-14 items-center justify-center rounded-lg bg-emerald-500 text-xl font-black text-white">
              {(s.company?.companyName || "KM").slice(0, 2).toUpperCase()}
            </div>
          )}
          <div>
            <div className="text-xl font-black">{s.company?.companyName || "KMDev"}</div>
            <div className="text-sm text-slate-500">{s.company?.developerName}</div>
            {s.company?.domain && <div className="text-xs text-emerald-600">{s.company.domain}</div>}
          </div>
        </div>
        <div className="text-right">
          <div className="text-lg font-bold uppercase tracking-wide text-emerald-600">{doc.title}</div>
          <div className="font-mono text-sm font-semibold">{doc.referenceNumber}</div>
          <div className="text-xs text-slate-500">Generated {formatDate(doc.generatedAt)}</div>
        </div>
      </div>

      {/* Parties */}
      <div className="mt-5 grid grid-cols-2 gap-6 text-sm">
        <div>
          <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">From</div>
          <div className="font-semibold">{s.company?.companyName}</div>
          <div className="text-slate-500">{s.company?.developerName}</div>
          {s.company?.email && <div className="text-slate-500">{s.company.email}</div>}
          {s.company?.phone && <div className="text-slate-500">{s.company.phone}</div>}
        </div>
        <div>
          <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">To</div>
          <div className="font-semibold">{s.client?.clientName}</div>
          {s.client?.companyName && <div className="text-slate-500">{s.client.companyName}</div>}
          {s.client?.email && <div className="text-slate-500">{s.client.email}</div>}
          {s.client?.phone && <div className="text-slate-500">{s.client.phone}</div>}
        </div>
      </div>

      {/* Project */}
      <div className="mt-5">
        <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Project</div>
        <Row label="Project Name" value={s.project?.projectName} />
        {s.project?.category && <Row label="Category" value={s.project.category} />}
        {s.project?.startDate && <Row label="Start Date" value={formatDate(s.project.startDate)} />}
        {s.project?.expectedCompletion && <Row label="Expected Completion" value={formatDate(s.project.expectedCompletion)} />}
        {s.project?.description && <p className="mt-2 text-sm leading-6 text-slate-600">{s.project.description}</p>}
      </div>

      {/* Pricing (quotes/invoices) */}
      {isInvoice && s.pricing && (
        <div className="mt-5">
          <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Pricing</div>
          <Row label="Base Project Price" value={currency(s.pricing.basePrice || 0)} />
          {(s.pricing.extras || []).filter((e: any) => !e.recurring).map((e: any) => (
            <Row key={e.key} label={e.label} value={currency(e.amount || 0)} />
          ))}
          <Row label="One-off Total" value={<span className="text-base font-bold text-emerald-600">{currency(s.pricing.total || 0)}</span>} />
          {(s.pricing.monthly || 0) > 0 && (
            <Row label="Monthly Services" value={`${currency(s.pricing.monthly)} / month`} />
          )}
        </div>
      )}

      {/* Payment status */}
      {s.payments && (s.payments.total > 0) && (
        <div className="mt-5">
          <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Payment Status</div>
          {(s.payments.entries || []).map((p: any, i: number) => (
            <Row key={i} label={`${p.label}${p.paid ? " ✓" : ""}`} value={`${currency(p.amount || 0)} — ${p.paid ? "Paid" : "Pending"}`} />
          ))}
          <Row label="Total Paid" value={currency(s.payments.paid || 0)} />
          <Row label="Outstanding" value={<span className="font-bold text-amber-600">{currency(s.payments.outstanding || 0)}</span>} />
        </div>
      )}

      {/* Handover checklist */}
      {isHandover && (
        <div className="mt-5">
          <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Handover Checklist</div>
          <div className="grid grid-cols-2 gap-2 text-sm">
            {(s.handover || []).map((h: any) => (
              <div key={h.key} className="flex items-center gap-2">
                <span className={h.done ? "text-emerald-600" : "text-slate-300"}>{h.done ? "☑" : "☐"}</span>
                {h.label}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Contract clauses */}
      {isContract && (s.clauses || []).length > 0 && (
        <div className="mt-5 space-y-3">
          <div className="text-xs font-semibold uppercase tracking-wide text-slate-400">Terms &amp; Conditions</div>
          {s.clauses.map((c: any) => (
            <div key={c.key}>
              <div className="text-sm font-semibold">{c.title}</div>
              <p className="text-sm leading-6 text-slate-600">{c.body}</p>
            </div>
          ))}
        </div>
      )}

      {/* Footer: signature + QR */}
      <div className="mt-8 flex items-end justify-between gap-6 border-t border-slate-200 pt-6">
        <div className="flex-1">
          <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Signature</div>
          {doc.signature && doc.signature.signedAt ? (
            <SignaturePreview signature={doc.signature} />
          ) : (
            <div className="mt-6 w-56 border-t border-slate-400 pt-1 text-xs text-slate-500">Authorised signature &amp; date</div>
          )}
        </div>
        <div className="text-center">
          {origin && <QRCodeSVG value={verifyUrl} size={96} level="M" />}
          <div className="mt-1 text-[10px] text-slate-500">Scan to verify</div>
          <div className="font-mono text-[10px] text-slate-400">{doc.referenceNumber}</div>
        </div>
      </div>

      <p className="mt-4 text-center text-[10px] text-slate-400">
        Verify the authenticity of this document at {origin}/verify/{doc.referenceNumber}
      </p>
    </div>
  );
}
